apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubebench-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubebench-operator
subjects:
  - kind: ServiceAccount
    name: kubebench-operator
    namespace: kubebench-operator # ✅ Add the correct namespace here
