apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubebenchjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: KubebenchJob
    plural: kubebenchjobs
    singular: kubebenchjob
    shortNames:
      - kbj
  scope: Namespaced
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                someField:
                  type: string

