apiVersion: kustomize.config.k8s.io/v1beta1  # Use v1 instead of v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - service.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - crd.yaml
  - config-map.yaml
  - deployment.yaml
  - application.yaml
  - cluster-info.yaml

namespace: kubebench-operator  # Applies namespace to all resources

commonLabels:
  kustomize.component: kubebench  # Correct way to add labels

configMapGenerator:
  - name: parameters
    files:  # Use "files" instead of deprecated "envs"
      - params.env  # Ensure this file exists

images:
  - name: gcr.io/kubeflow-images-public/kubebench/kubebench-operator-v1alpha2
    newName: gcr.io/kubeflow-images-public/kubebench/kubebench-operator-v1alpha2
    newTag: bc682c1

patches:
  - path: service-annotation-patch.yaml
    target:
      kind: Service
      name: kubebench-service  # Must match exactly
      version: v1  # 

# configurations:  # Remove unless params.yaml is a Kustomize transformer config
