apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- virtual-service.yaml

vars:
  - name: namespace
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: parameters
      namespace: kubebench-operator  # Ensure this is the correct namespace
    fieldref:
      fieldPath: data.namespace

  - name: clusterDomain
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: parameters
      namespace: kubebench-operator  # Ensure this is the correct namespace
    fieldref:
      fieldPath: data.clusterDomain
  
configurations:
- params.yaml
